name = "UwUcraft"
author = "shantih19"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d7ab1a030f6ff8ace685cec13b7235a4f2d01edea5fd196b43b8e236553eeb1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
